### ISSUE TITLE
Disaster for Googling error messages

### ISSUE THREAD

**Issue by fulldecent** [CpanelInc/cplocales#5]
This document is the first search result for every error message that spits out of CPanel.

And in the example of "You do not have permission to use the IP address", it is the only search result.

Please consider linking to the preferred support mechanism where users may find solutions to errors such as this.

**Comment by bk2204** [comment]
Thanks for the heads up.  I'll try to provide a link to better support methods.

**Comment by ColMelvin** [comment]
Note added to README file.

**Comment by fulldecent** [comment]
Appreciated, thank you
