### ISSUE TITLE
How to easily translate with .yaml files?

### ISSUE THREAD

**Issue by cenourinha** [CpanelInc/cplocales#8]
Hi there,

I want to help improve the Portuguese (pt_PT) translation, but i find it very difficult to translate and manage translation with yaml files. What is the best way to translate this way?

I reached the Weblate ( https://weblate.org/pt/ ) website, but it seems to only support po/mo format.

**Comment by cenourinha** [comment]
Hey @bk2204, do you mind to help?

**Comment by travisellis** [comment]
Hi,

You can translate the files using any text editor program. 

A guide to understanding the variables can be found at: https://documentation.cpanel.net/display/SDK/Guide+to+Template+Toolkit+-+Localization+in+Template+Toolkit <https://documentation.cpanel.net/display/SDK/Guide+to+Template+Toolkit+-+Localization+in+Template+Toolkit>
And more information on Bracket notation can be found at https://documentation.cpanel.net/display/SDK/Guide+to+Locales+-+For+Translators <https://documentation.cpanel.net/display/SDK/Guide+to+Locales+-+For+Translators>

Thanks,
Travis

**Comment by cenourinha** [comment]
Isn't there any tool that will help make the translation easier? An editor with side-by-side translation?

**Comment by bk2204** [comment]
I'm not aware of any tool that autoconverts between the YAML files and the .po files.  Also, these files use the Locale::Maketext bracket notation, not gettext, so even if there were such a tool, it would not necessarily be useful in this case.  However, I can probably hack something together over the next day or two that will work in this case.  Let me look at it.

**Comment by bk2204** [comment]
I've created a pair of tools called yaml2po and po2yaml that live in [bk2204/yaml2po](https://github.com/bk2204/yaml2po).  You'll need Perl with YAML::Syck.

On a cPanel system, running `/usr/local/cpanel/3rdparty/bin/perl bin/yaml2po /path/to/pt.yaml > /path/to/pt.po` should work.  Debian's Perl with the libyaml-syck-perl package works as well.

**Comment by bk2204** [comment]
I'm assuming this tool is adequate for your needs, so I'm going to close this issue.
